-- 문제 : 5월 식품들의 총매출 조회하기
-- 풀이 일자 : 2025.10.22
-- 설명 : https://school.programmers.co.kr/learn/courses/30/lessons/131117

SELECT A.PRODUCT_ID, B.PRODUCT_NAME, TOTAL_AMOUNT * PRICE TOTAL_SALES
FROM (SELECT PRODUCT_ID, SUM(AMOUNT) TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE YEAR(PRODUCE_DATE) = '2022' and MONTH(PRODUCE_DATE) = '05'
    GROUP BY PRODUCT_ID) A
LEFT JOIN FOOD_PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC