-- 문제 : 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기
-- 풀이 일자 : 2025.10.30
-- 설명 : https://school.programmers.co.kr/learn/courses/30/lessons/151139

WITH RENTAL_COUNT AS (
    SELECT CAR_ID, COUNT(*) CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= "2022-08-01" AND START_DATE <= "2022-10-31"
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
SELECT MONTH(START_DATE) MONTH, CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID FROM RENTAL_COUNT)
    AND START_DATE >= "2022-08-01" AND START_DATE <= "2022-10-31"
GROUP BY MONTH, CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;