-- 문제 : 자동차 대여 기록에서 대여중 / 대여 가능 여부 구분하기
-- 풀이 일자 : 2025.09.30
-- 설명 : https://school.programmers.co.kr/learn/courses/30/lessons/157340

SELECT DISTINCT A.CAR_ID , CASE WHEN B.CAR_ID IS NOT NULL THEN '대여중' ELSE '대여 가능' END AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
LEFT JOIN (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-10-16' AND '2022-10-16'<= END_DATE
) B ON A.CAR_ID = B.CAR_ID
ORDER BY A.CAR_ID DESC
;

SELECT 
    CAR_ID,
    CASE 
        WHEN MAX(CASE WHEN '2022-10-16' BETWEEN start_date AND end_date THEN 1 ELSE 0 END) = 1 
        THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;