-- 문제 : 자동차 대여 기록 별 대여 금액 구하기
-- 풀이 일자 : 2026.04.17
-- 설명 : https://school.programmers.co.kr/learn/courses/30/lessons/151141

WITH STEP1 AS (
    SELECT A.HISTORY_ID, CAR_TYPE, DAILY_FEE, DATEDIFF(END_DATE, START_DATE) + 1 DD,
    CASE  
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
        ELSE NULL
    END DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
    LEFT JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
    WHERE CAR_TYPE = '트럭'
)

SELECT HISTORY_ID,
    IF(DISCOUNT_RATE IS NULL, DAILY_FEE * DD, TRUNCATE(DAILY_FEE * DD * (100-DISCOUNT_RATE) * 0.01, 0)) FEE
FROM STEP1 A LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
    ON A.CAR_TYPE = B.CAR_TYPE AND A.DURATION_TYPE = B.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC
;

-- 하드 코딩 제거한 버전
WITH BASE AS (
    SELECT 
        A.HISTORY_ID,
        B.CAR_TYPE,
        B.DAILY_FEE,
        DATEDIFF(A.END_DATE, A.START_DATE) + 1 AS DD
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
    JOIN CAR_RENTAL_COMPANY_CAR B 
        ON A.CAR_ID = B.CAR_ID
    WHERE B.CAR_TYPE = '트럭'
)

SELECT 
    A.HISTORY_ID,
    TRUNCATE(
        A.DAILY_FEE * A.DD * (100 - IFNULL(B.DISCOUNT_RATE, 0)) / 100
    , 0) AS FEE
FROM BASE A
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
    ON A.CAR_TYPE = B.CAR_TYPE
    AND B.DURATION_TYPE = (
        SELECT DURATION_TYPE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE CAR_TYPE = A.CAR_TYPE
          AND A.DD >= CAST(REPLACE(DURATION_TYPE, '일 이상', '') AS UNSIGNED)
        ORDER BY CAST(REPLACE(DURATION_TYPE, '일 이상', '') AS UNSIGNED) DESC
        LIMIT 1
    )
ORDER BY FEE DESC, HISTORY_ID DESC;