-- 문제 : 저자 별 카테고리 별 매출액 집계하기
-- 풀이 일자 : 2025.10.23
-- 설명 : https://school.programmers.co.kr/learn/courses/30/lessons/144856

WITH SALES_INFO AS (
    SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '01'
    GROUP BY BOOK_ID
)
SELECT A.AUTHOR_ID, C.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE * B.TOTAL_SALES) TOTAL_SALES
FROM BOOK A
LEFT JOIN SALES_INFO B ON A.BOOK_ID = B.BOOK_ID
LEFT JOIN AUTHOR C ON A.AUTHOR_ID = C.AUTHOR_ID
GROUP BY A.AUTHOR_ID, A.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC
;