-- 문제 : 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기
-- 풀이 일자 : 2025.10.23
-- 설명 : https://school.programmers.co.kr/learn/courses/30/lessons/157339

WITH INFO AS (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = "30일 이상"
)
SELECT *
FROM (
    SELECT A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE * 30 * (100-B.DISCOUNT_RATE)/100,0) FEE
    FROM CAR_RENTAL_COMPANY_CAR A
    LEFT JOIN INFO B ON A.CAR_TYPE = B.CAR_TYPE
    WHERE (A.CAR_TYPE = '세단' OR A.CAR_TYPE = 'SUV')
        AND CAR_ID NOT IN (SELECT DISTINCT CAR_ID
                            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                            WHERE ("2022-11-01" <= END_DATE ) AND (START_DATE <= "2022-11-30"))
) D
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
;