-- 문제 : 상품 별 오프라인 매출 구하기
-- 풀이 일자 : 2025.09.08
-- 설명 : https://school.programmers.co.kr/learn/courses/30/lessons/131533

SELECT PRODUCT_CODE, SALES_AMOUNT * PRICE SALES
FROM (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) SALES_AMOUNT
      FROM OFFLINE_SALE
      GROUP BY PRODUCT_ID
     ) A
LEFT JOIN PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC
;