-- 문제 : 조건에 맞는 사용자와 총 거래금액 조회하기
-- 풀이 일자 : 2025.10.28
-- 설명 : https://school.programmers.co.kr/learn/courses/30/lessons/164668

WITH TABLE_A AS (
SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING TOTAL_SALES >= 700000
)
SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM TABLE_A
LEFT JOIN USED_GOODS_USER ON TABLE_A.WRITER_ID = USED_GOODS_USER.USER_ID
ORDER BY TOTAL_SALES ASC
;