-- 문제 : 카테고리 별 상품 개수 구하기
-- 풀이 일자 : 2026.05.05, 2026.06.25
-- 설명 : https://school.programmers.co.kr/learn/courses/30/lessons/131529

SELECT CATEGORY, COUNT(*) PRODUCTS
FROM (
    SELECT SUBSTRING(PRODUCT_CODE, 1, 2) CATEGORY
    FROM PRODUCT
    ) A
GROUP BY CATEGORY
ORDER BY CATEGORY ASC
;

-- 2026.06.25
WITH NEW_PRODUCT AS (
    SELECT SUBSTRING(PRODUCT_CODE, 1, 2) CATEGORY, PRODUCT_ID
    FROM PRODUCT
)
SELECT CATEGORY, COUNT(*) AS PRODUCTS
FROM NEW_PRODUCT
GROUP BY CATEGORY
ORDER BY CATEGORY ASC
;