-- 문제 : ROOT 아이템 구하기
-- 풀이 일자 : 2025.10.29
-- 설명 : https://school.programmers.co.kr/learn/courses/30/lessons/273710

WITH ROOT_ITEM AS (
    SELECT DISTINCT ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NULL
)
SELECT ROOT_ITEM.ITEM_ID, ITEM_NAME
FROM ROOT_ITEM
LEFT JOIN ITEM_INFO ON ROOT_ITEM.ITEM_ID = ITEM_INFO.ITEM_ID
ORDER BY ROOT_ITEM.ITEM_ID ASC
;