-- 문제 : 특정 세대의 대장균 찾기
-- 풀이 일자 : 2026.04.16
-- 설명 : https://school.programmers.co.kr/learn/courses/30/lessons/301650

WITH RECURSIVE ECOLI AS (

    SELECT ID, PARENT_ID, 1 TH
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT ECOLI_DATA.ID, ECOLI_DATA.PARENT_ID, TH+1
    FROM ECOLI INNER JOIN ECOLI_DATA ON ECOLI.ID = ECOLI_DATA.PARENT_ID
    # WHERE ECOLI_DATA.ID NOT IN (SELECT ID FROM ECOLI)
)

SELECT ID
FROM ECOLI
WHERE TH = 3
ORDER BY ID
;

-- 풀이 일자 : 2026.04.29
WITH RECURSIVE ECOLI_DATA_INFO AS  (
    SELECT ID, 1 AS TH
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT B.ID, TH+1
    FROM ECOLI_DATA_INFO A LEFT JOIN ECOLI_DATA B ON A.ID = B.PARENT_ID
    WHERE B.ID IS NOT NULL
)

SELECT ID
FROM ECOLI_DATA_INFO
WHERE TH = 3
ORDER BY ID
;